### ISSUE TITLE
Initial content of Software Development Toolkit

### ISSUE THREAD

**Issue by iperdomo** [unicef/ooi-toolkit-software#1]
- [x] Move content to `ooi-toolkit-software` repo
- [x] Incorporate feedack from team members

**Comment by justwheel** [comment]
Hey @iperdomo, perhaps these categories on the Open Source Inventory could be migrated here. What do you think?

- [Data Ethics & Transparency](https://unicef.github.io/inventory/data/) (this one is a maybe)
- [Developer Tools & Automation](https://unicef.github.io/inventory/dev-tools/)
- [Reproducibility](https://unicef.github.io/inventory/reproducibility/)

The Dev Tools and Reproducibility sections are pretty slim already, so migrating those two should be relatively simple.

**Comment by justwheel** [comment]
@iperdomo and I met yesterday. The plan is as follows:

1. Relocate the _Continuous Integration (CI)_ and _Reproducibility reading list_ pages into this toolkit
2. Once relocated, set up redirects so old links send visitors to this toolkit; if redirect is not possible, delete the index page and manually add a link to the new page in the O.S. Inventory

@iperdomo, did you want me to initiate the move, or do you want to import the O.S. Inventory content in once your toolkit is further along? Let me know. 🙂
